### ISSUE TITLE
Different CustomModelData for all modes

### ISSUE THREAD

**Issue by iKoary** [TWME-TW/DebugStickPro#20]
It would be nice to be able to change the CustomModelData depending on the selected mode

**Comment by TWME-TW** [comment]
> It would be nice to be able to change the CustomModelData depending on the selected mode

Okay, I might make an additional plugin for this functionality. It will be completed as soon as this weekend (not guaranteed)

**Comment by iKoary** [comment]
> Okay, I might make an additional plugin for this functionality. It will be completed as soon as this weekend (not guaranteed)

Why not just add an option in the config of this plugin, instead of creating a new one?

**Comment by TWME-TW** [comment]
> > Okay, I might make an additional plugin for this functionality. It will be completed as soon as this weekend (not guaranteed)
> 
> Why not just add an option in the config of this plugin, instead of creating a new one?

Maybe, I think I'll add it to the feature list for version 0.5.0.

**Comment by iKoary** [comment]
Is there still any chance this will be added?

**Comment by TWME-TW** [comment]
> Is there still any chance this will be added?

Yes, I will add this feature, it's just that it took me too long to write a feature like Axiom's Tinker (it's not finished yet)

**Comment by TWME-TW** [comment]
@iKoary When the mode changes, do you want the CustomModelData of all debug sticks on the player to change?

**Comment by iKoary** [comment]
> @iKoary When the mode changes, do you want the CustomModelData of all debug sticks on the player to change?

I think it would be better if CustomModelData of only one debug stick changes, the one in your main hand

**Comment by TWME-TW** [comment]
> > @iKoary When the mode changes, do you want the CustomModelData of all debug sticks on the player to change?
> 
> I think it would be better if CustomModelData of only one debug stick changes, the one in your main hand

Do you want the debug stick's mode to be based on the mode of the debug stick the player is holding?

What I mean is that when debug sticks A, B, and C have different modes, the player can switch the debug stick's mode by switching between the debug sticks.

**Comment by iKoary** [comment]
> Do you want the debug stick's mode to be based on the mode of the debug stick the player is holding?
> 
> What I mean is that when debug sticks A, B, and C have different modes, the player can switch the debug stick's mode by switching between the debug sticks.

Yes, if it's possible

**Comment by TWME-TW** [comment]
@iKoary If possible, please test the latest version
https://github.com/TWME-TW/DebugStickPro/releases/tag/0.4.11

**Comment by iKoary** [comment]
> @iKoary If possible, please test the latest version https://github.com/TWME-TW/DebugStickPro/releases/tag/0.4.11

I tested it, but CustomModelData doesn't changes with mode, it's always the ClassicMode model

**Comment by TWME-TW** [comment]
Oops, I'm so sorry, I forgot to update the player's inventory

**Comment by TWME-TW** [comment]
After testing, the latest version has fixed this problem @iKoary
