### ISSUE TITLE
Trap door open status is not available.

### ISSUE THREAD

**Issue by KAZUTO0110** [TWME-TW/DebugStickPro#7]
I have been looking for a plugin to customize debugstick for a long time.
Thank you for creating such a plugin.

When I click on the iron trapdoor in classic mode in DSP, the status of open is not available.
(I am able to do this with debugstick in Vanilla).
Can you please make the status of open available?

Blacklist is false.
ServerVer:1.19.4(paper#550)
DSPver:0.4.3

**Comment by TWME-TW** [comment]
> I have been looking for a plugin to customize debugstick for a long time. Thank you for creating such a plugin.
> 
> When I click on the iron trapdoor in classic mode in DSP, the status of open is not available. (I am able to do this with debugstick in Vanilla). Can you please make the status of open available?
> 
> Blacklist is false. ServerVer:1.19.4(paper#550) DSPver:0.4.3

Fixed in version 0.4.4 https://github.com/TWME-TW/DebugStickPro/releases/tag/0.4.4

**Comment by KAZUTO0110** [comment]
Resolved. Thank you.
